name: integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'go.mod'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install Pulumi CLI
        uses: pulumi/actions@v6
        with:
          pulumi-version: latest

      - name: Run integration tests
        run: make test_examples
        env:
          DAGSTER_CLOUD_ORGANIZATION: ${{ secrets.DAGSTER_CLOUD_ORGANIZATION }}
          DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
